version: "3"

services:
    ackrep-django:
        environment:
            DJANGO_MANAGEPY_MIGRATE: "on"
        build:
            context: ..
            dockerfile: ./ackrep_deployment/dockerfiles/ackrep_core/Dockerfile
        ports:
            - "8000:8000"
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.ackrep-django.rule=Host(`testing.ackrep.eu`)'
            # - 'traefik.http.routers.ackrep-django.tls.domain[0].main=ackrep.eu'
            # - 'traefik.http.routers.ackrep-django.tls.domain[0].sans=*.ackrep.eu'
            - 'traefik.http.routers.ackrep-django.tls=true'
            - 'traefik.http.routers.ackrep-django.tls.certresolver=lets-encrypt'

    traefik:
        image: traefik:2.1
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./traefik:/etc/traefik
            - /var/run/docker.sock:/var/run/docker.sock:ro
